apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector: 
    matchLabels: 
      app: redis
  template:
    metadata: 
      labels: 
        app: redis
    spec:
      containers: 
        -
          image: redis:6.0.8-alpine@sha256:ee1dd9d560836485dbee7b863cd52307b09c6a2e351bf8c23cface356508e9b1
          name: redis
          ports: 
            -
              containerPort: 6379
          volumeMounts:
            -
              mountPath: /data
              name: redis
      volumes:
        -
          name: redis
          persistentVolumeClaim:
            claimName: redis
      
              
      
