################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rng-ds
spec:
  selector:
    matchLabels:
      service-po: rng-po
  template:
    metadata:
      labels:
        service-po: rng-po
    spec:
      containers:
      -
        image: secobau/dockercoins:rng-1.7
        name: rng-container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher-deploy
spec:
  selector:
    matchLabels:
      service-po: hasher-po
  template:
    metadata:
      labels:
        service-po: hasher-po
    spec:
      containers:
      -
        image: secobau/dockercoins:hasher-1.7
        name: hasher-container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
spec:
  selector:
    matchLabels:
      service-po: redis-po
  template:
    metadata:
      labels:
        service-po: redis-po
    spec:
      containers:
      -
        image: redis
        name: redis-container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deploy
spec:
  selector:
    matchLabels:
      service-po: webui-po
  template:
    metadata:
      labels:
        service-po: webui-po
    spec:
      containers:
      -
        image: secobau/dockercoins:webui-1.7
        name: webui-container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
spec:
  selector:
    matchLabels:
      service-po: worker-po
  template:
    metadata:
      labels:
        service-po: worker-po
    spec:
      containers:
      -
        image: secobau/dockercoins:worker-1.7
        name: worker-container
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hasher-netpol
spec:
  podSelector:
    matchLabels:
      service-po: hasher-po
  ingress:
    -
      from:
        -
          podSelector:
            matchLabels:
              service-po: worker-po
      ports:
        -
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-netpol
spec:
  podSelector:
    matchLabels:
      service-po: redis-po
  ingress:
    -
      from:
        -
          podSelector:
            matchLabels:
              service-po: webui-po
        -
          podSelector:
            matchLabels:
              service-po: worker-po
      ports:
        -
          port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rng-netpol
spec:
  podSelector:
    matchLabels:
      service-po: rng-po
  ingress:
    -
      from:
        -
          podSelector:
            matchLabels:
              service-po: worker-po
      ports:
        -
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
spec:
  ports:
  -
    port: 8080
  selector:
    service-po: hasher-po
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  -
    port: 6379
  selector:
    service-po: redis-po
---
apiVersion: v1
kind: Service
metadata:
  name: rng
spec:
  ports:
  -
    port: 8080
  selector:
    service-po: rng-po
---
apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  ports:
  -
    port: 8080
  selector:
    service-po: webui-po
  type: NodePort
################################################################################
