#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
networks:
  hasher:
    internal: true
  redis:
    internal: true
  rng:
    internal: true
  webui:
    external: true
  worker:
    internal: true
services:
  hasher:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: secobau/dockercoins:hasher
    networks:
    - hasher
  redis:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: redis
    networks:
    - redis
  rng:
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == worker
    image: secobau/dockercoins:rng
    networks:
    - rng
  webui:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: secobau/dockercoins:webui
    networks:
    - redis
    - webui
    ports:
    - "8080:8080"
  worker:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: secobau/dockercoins:worker
    networks:
    - hasher
    - redis
    - rng
    - worker
version: "3.8"
#########################################################################
