name: swarm
on:
  push: 
    branches: [dev]
jobs: 
  swarm: 
    env:
      mode: swarm
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      run: |
      
        set -x
        
        project=$(basename $GITHUB_REPOSITORY)
        compose=etc/$mode/$project.yaml
        date=$(date +%s)

        for image in hasher rng webui worker
          do
            docker build -t openshiftacademiaonline/dockercoins-dev:latest-$image --no-cache $image/
          done
        docker image ls | grep dockercoins              

        docker swarm init

        sed -i s/worker/manager/ $compose
        docker stack deploy -c $compose $project
        
        while true
          do
            sleep 1
            docker service ls
            docker service ls | grep '\([0-9]\)/\1' && break
          done
